name: deadbolt
description: "Bitcoin descriptor analyzer"
publish_to: 'none'
version: 1.0.0+26021420

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_deadbolt:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  flutter_bloc: ^9.1.1
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.6
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.25.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"
