name: deadbolt
description: "Bitcoin descriptor analyzer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_deadbolt:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  flutter_bloc: ^9.1.1
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.25.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
